language: elixir
elixir:
  - 1.10
otp_release:
  - 22.0
services:
  - postgresql
env:
  - MIX_ENV=test
script:
  - mix format --check-formatted
  - mix credo
  - mix dialyzer
  - mix test --cover
cache:
  directories:
    - deps
    - _build
    - priv/plts
